# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 10:57
from __future__ import unicode_literals

import acra.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=acra.django.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=acra.django.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_html',
            field=acra.django.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=acra.django.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=acra.django.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary_html',
            field=acra.django.TextField(),
        ),
    ]
